name: Build

on:
  push:
    branches:
      - master
    paths:
      - containers/**
      - .github/workflows/build.yml
  pull_request:
    branches:
      - master
    paths:
      - containers/**
      - .github/workflows/build.yml

env:
  REGISTRY_IMAGE: medzik/qemu-user-static
  PLATFORMS: linux/amd64,linux/386,linux/arm64,linux/arm/v7,linux/arm64/v8,linux/riscv64,linux/ppc64le,linux/s390x

jobs:
  qemu-user-static:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push "latest" container
        uses: docker/build-push-action@v5
        with:
          context: containers/latest
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: ${{ env.REGISTRY_IMAGE }}:latest

      - name: Generate register conainter files
        run: |
          cp -p "containers/latest/register.sh" "containers/register/"
          cp -p "containers/latest/Dockerfile" "containers/register/"
          sed -i '/^COPY --from=download_qemu/ s/^/#/' "containers/register/Dockerfile"

      - name: Build and push "register" container
        uses: docker/build-push-action@v5
        with:
          context: containers/register
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: ${{ env.REGISTRY_IMAGE }}:register
